craigslist_jr/config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'
  get  '/categories' => 'categories#index'
  get 'categories/:category_id/articles' => 'articles#index', :as => 'category_articles'
  get '/categories/:category_id/articles/new' => 'articles#new', :as => 'new_article'
  patch '/categories/:category_id/articles/:article_id' => 'articles#update', :as => 'category_article'
  get 'categories/:category_id/articles/:article_id/edit' => 'articles#edit'
  post '/categories/:category_id/articles' => 'articles#create'

end

craigslist_jr/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :body, :category, { presence: true }

  belongs_to :category
end

craigslist_jr/app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, { null: false }

  has_many :articles
end

craigslist_jr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

craigslist_jr/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
  end

  def show
  end

  def new
    @category = Category.find(params[:category_id])
    @article = Article.new
  end

  def edit
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:article_id])
  end

  def create
    @category = Category.find(params[:category_id])
    @article = @category.articles.create(article_params)
    redirect_to category_articles_path(@category)
  end

  def update
    @article = Article.find(params[:article_id])
    @article.update(article_params)
    # if you want to keep working on this, use redirect_to
  end

  def destroy
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

craigslist_jr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

craigslist_jr/app/helpers/application_helper.rb
module ApplicationHelper
end

craigslist_jr/app/views/articles/_form.html.erb
<%= form_for [@category, @article] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

craigslist_jr/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "articles/form" %>

craigslist_jr/app/views/articles/index.html.erb
<%= link_to 'New Article', new_article_path %>
<ul>
  <% @category.articles.each do |article| %>
    <li><%= article.title %></li>
  <% end %>
</ul>

craigslist_jr/app/views/articles/new.html.erb
<%= form_for([@category, @category.articles.build]) do |f| %>
  <%= render "articles/form" %>
<% end %>

craigslist_jr/app/views/articles/show.html.erb
<p>hello</p>

craigslist_jr/app/views/categories/index.html.erb
<h1>Welcome to Craigslist Jr.<h1>
<section>
  <ul>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category.name %>
      </li>
    <% end %>
  </ul>
</section>

craigslist_jr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>